# Lab 6-Basic Data Manipulation and Visualization



# **Assignment Submission Guidelines**

Please follow the guidelines below for submitting your assignment:

1. **Submission Deadline:**
   - All assignments must be submitted **no later than 11:59 PM Next Wednesday (07/15) Midnight**.
   - Late submissions will not be accepted unless prior arrangements have been made by the instructor.

2. **Required Files:**
   - **Jupyter Notebook file (.ipynb):** Submit the Jupyter Notebook file you used to complete the assignment. The file should contain your well-commented code.
   - **PDF Version (.pdf file):** Additionally, submit a PDF version of your Python code. This can be a printout or export of your script, showing all the code with any necessary explanations or output results included.

3. **File Naming Convention:**
   - Please name your files as follows: `Lastname_Firstname_AssignmentName`
   - Example: `Alex_John_Lab6.ipynb` and `Alex_Johb_Lab6.pdf`

4. **Technical Issues:**
   - If you encounter any technical issues with Canvas or your submission, please contact the TAs immediately **before the deadline** to avoid penalties.

## 1. Load and Inspect Data (10 Points)



Load the 2012_Workplace_Fatalities_by_State.csv file into a Pandas DataFrame.

Display the first 50 rows of data in the first column.

Replace all missing values with 0.

In [73]:
import pandas as pd

df = pd.read_csv('2012_Workplace_Fatalities_by_State.csv')

display(df.head(50))

df = df.fillna(0)

,State,"Number of Fatalities, 2012","Rate of Fatalities, 2012","State Rank, Fatalities 2012",Number of Injuries/Illnesses 2012,Injuries/Illnesses 2012 Rate,Penalties FY 2013 (Average $),Penalties FY 2013 (Rank),Inspectors,Years to Inspect Each Workplace Once,State or Federal Program
0,"South Carolina\n(33.99882060100049, -81.045367...",63.0,3.5,25.0,36200.0,3.0,492.0,49.0,24.0,111.0,State
1,"West Virginia\n(38.665511497000466, -80.712639...",49.0,6.9,46.0,19800.0,4.1,1798.0,27.0,7.0,173.0,Federal
2,"Massachusetts\n(42.27687306500047, -72.0826898...",44.0,1.4,1.0,69700.0,3.1,1929.0,21.0,33.0,123.0,Federal
3,"Tennessee\n(35.680943063000484, -85.7744864219...",101.0,3.8,30.0,65100.0,3.5,727.0,45.0,30.0,82.0,State
4,"Oklahoma\n(35.472034350000456, -97.52106845499...",97.0,6.1,42.0,39000.0,3.6,1872.0,24.0,19.0,131.0,Federal
5,"Illinois\n(40.48501278700047, -88.99770813999965)",146.0,2.5,10.0,124900.0,3.2,1876.0,23.0,74.0,137.0,Federal
6,"Nebraska\n(41.64104043900045, -99.36571864599966)",48.0,5.2,38.0,24300.0,3.9,2565.0,5.0,9.0,128.0,Federal
7,"Delaware\n(39.00883351400046, -75.57773943699965)",14.0,3.1,18.0,7900.0,2.8,2406.0,6.0,5.0,175.0,Federal
8,"Hawaii\n(21.30485166200043, -157.85774691599974)",20.0,3.4,22.0,13700.0,3.8,964.0,39.0,20.0,79.0,State
9,"Iowa\n(42.469404401000475, -93.81648936699969)",97.0,6.6,44.0,45600.0,4.5,790.0,43.0,26.0,98.0,State
10,"Arizona\n(34.865973091000455, -111.76380949799...",60.0,2.3,6.0,54400.0,3.2,891.0,40.0,30.0,126.0,State
11,"Florida\n(28.932042899000464, -81.92895558499964)",218.0,2.7,15.0,NaN,NaN,1821.0,25.0,60.0,238.0,Federal
12,"Virginia\n(37.54268075100049, -78.45788924199968)",149.0,3.8,30.0,66200.0,2.7,726.0,46.0,48.0,82.0,State
13,"Missouri\n(38.63579372300046, -92.56629737199967)",88.0,3.3,21.0,60300.0,3.3,1931.0,20.0,26.0,118.0,Federal
14,"Michigan\n(44.66131575600048, -84.71438724399968)",137.0,3.4,22.0,105500.0,4.0,542.0,48.0,63.0,45.0,State
15,"Indiana\n(39.76691364600049, -86.14995579899966)",115.0,4.2,33.0,77900.0,3.9,1054.0,34.0,39.0,104.0,State
16,"North Carolina\n(35.46622388600048, -79.159249...",146.0,3.5,25.0,75900.0,2.9,996.0,38.0,104.0,60.0,State
17,"New Hampshire\n(43.6559537330005, -71.50035726...",14.0,2.2,4.0,NaN,NaN,2243.0,8.0,7.0,119.0,Federal
18,"New Mexico\n(34.52088247800049, -106.240577688...",39.0,4.8,35.0,19900.0,3.9,998.0,37.0,9.0,191.0,State
19,"Pennsylvania\n(40.79373106100047, -77.86069775...",194.0,3.4,22.0,155300.0,3.9,1916.0,22.0,57.0,125.0,Federal
20,"South Dakota\n(44.35313342000046, -100.3735281...",31.0,6.7,45.0,NaN,NaN,2346.0,7.0,NaN,521.0,Federal
21,"New York\n(42.82700023900048, -75.54396639699968)",202.0,2.4,8.0,146300.0,2.5,2016.0,17.0,105.0,184.0,Federal
22,"Utah\n(39.36070374600047, -111.5871285339997)",39.0,3.0,17.0,27700.0,3.4,1053.0,35.0,22.0,81.0,State
23,"Maine\n(45.254228663000504, -68.98502952999962)",19.0,3.2,20.0,21200.0,5.6,2083.0,14.0,8.0,80.0,Federal
24,"Montana\n(47.066526051000494, -109.42441687999...",34.0,7.3,47.0,13300.0,5.0,1983.0,18.0,7.0,135.0,Federal
25,"Vermont\n(43.62538292400046, -72.51763944499965)",11.0,3.5,25.0,9900.0,5.0,1008.0,36.0,9.0,68.0,State
26,"Arkansas\n(34.748651751000466, -92.27448794899...",63.0,5.4,39.0,26600.0,3.2,2569.0,4.0,9.0,237.0,Federal
27,"Nevada\n(39.49324126500045, -117.07183978499972)",42.0,3.6,29.0,32400.0,4.1,2133.0,13.0,44.0,49.0,State
28,"Kentucky\n(37.645973909000475, -84.77496612599...",91.0,4.9,37.0,48900.0,4.1,3254.0,2.0,39.0,124.0,State
29,"Maryland\n(39.2905806980005, -76.60925970899967)",72.0,2.6,12.0,51900.0,3.1,685.0,47.0,48.0,108.0,State
30,"Alabama\n(32.84057327200048, -86.63185803899967)",84.0,4.3,34.0,41200.0,3.3,1803.0,26.0,24.0,94.0,Federal
31,"Connecticut\n(41.56266394200048, -72.649837536...",36.0,2.1,3.0,43800.0,3.9,1735.0,30.0,24.0,107.0,Federal
32,"Oregon\n(44.567446178000466, -120.15502977999972)",43.0,2.6,12.0,42900.0,3.9,363.0,50.0,75.0,31.0,State
33,"Colorado\n(38.84384047000049, -106.13360888799...",82.0,3.5,25.0,NaN,NaN,1649.0,31.0,28.0,122.0,Federal
34,"Ohio\n(40.06021029700048, -82.40425685299965)",161.0,3.1,18.0,113600.0,3.2,2156.0,11.0,53.0,112.0,Federal
35,"Wyoming\n(43.23554147100049, -108.10982744299969)",35.0,12.2,49.0,6500.0,3.5,1777.0,28.0,9.0,101.0,State
36,"Minnesota\n(46.35564867700049, -94.79419697699...",70.0,2.6,12.0,67500.0,3.8,768.0,44.0,58.0,57.0,State
37,"Kansas\n(38.34774033400049, -98.20077655499966)",76.0,5.7,41.0,33400.0,3.6,1971.0,19.0,16.0,110.0,Federal
38,"Idaho\n(43.682630058000484, -114.3637261449997)",19.0,2.7,15.0,NaN,NaN,1449.0,33.0,9.0,108.0,Federal
39,"Washington\n(47.522287905000496, -120.47002746...",67.0,2.2,4.0,89300.0,4.8,791.0,42.0,111.0,50.0,State
40,"Wisconsin\n(44.3931903350005, -89.81636715299965)",114.0,4.0,32.0,72900.0,4.0,2207.0,9.0,36.0,104.0,Federal
41,"Mississippi\n(32.74551123200047, -89.538027644...",63.0,5.5,40.0,NaN,NaN,1515.0,32.0,14.0,112.0,Federal
42,"Louisiana\n(31.312662564000448, -92.4456755459...",116.0,6.4,43.0,30600.0,2.3,1765.0,29.0,16.0,206.0,Federal
43,"Georgia\n(32.83968004200045, -83.62757601199968)",101.0,2.5,10.0,74800.0,2.8,2061.0,15.0,49.0,138.0,Federal
44,"Rhode Island\n(41.70828281900049, -71.52246918...",8.0,1.7,2.0,NaN,NaN,2023.0,16.0,7.0,103.0,Federal
45,"Alaska\n(64.84507923900048, -147.72205669099972)",31.0,8.9,48.0,9700.0,4.6,889.0,41.0,11.0,58.0,State
46,"New Jersey\n(40.1305700530005, -74.27368565099...",92.0,2.4,8.0,80900.0,3.1,2151.0,12.0,67.0,123.0,Federal
47,"North Dakota\n(47.47531738700047, -100.1184259...",65.0,17.7,50.0,NaN,NaN,3045.0,3.0,8.0,111.0,Federal
48,"Texas\n(31.827243635000457, -99.4267664729997)",536.0,4.8,35.0,203200.0,2.7,2187.0,10.0,98.0,136.0,Federal
49,"California\n(37.638640488000476, -120.99999889...",375.0,2.3,6.0,345400.0,3.5,6422.0,1.0,216.0,179.0,State

##  2. Clean up the state names (10 Points)

The first column that contains both U.S. state names and their coordinates in a messy format. Please remove the coordinates between the state names. Add two columns of longitude and latitude to the data.

In [80]:
df = pd.read_csv('2012_Workplace_Fatalities_by_State.csv')

df['State'] = df['State'].str.split('\n')

df['Latitude'] = df['State'].str[1]

df.head()

,State,"Number of Fatalities, 2012","Rate of Fatalities, 2012","State Rank, Fatalities 2012",Number of Injuries/Illnesses 2012,Injuries/Illnesses 2012 Rate,Penalties FY 2013 (Average $),Penalties FY 2013 (Rank),Inspectors,Years to Inspect Each Workplace Once,State or Federal Program,Latitude
0,"[South Carolina, (33.99882060100049, -81.04536...",63.0,3.5,25.0,36200.0,3.0,492.0,49.0,24.0,111.0,State,"(33.99882060100049, -81.04536765699964)"
1,"[West Virginia, (38.665511497000466, -80.71263...",49.0,6.9,46.0,19800.0,4.1,1798.0,27.0,7.0,173.0,Federal,"(38.665511497000466, -80.71263935099967)"
2,"[Massachusetts, (42.27687306500047, -72.082689...",44.0,1.4,1.0,69700.0,3.1,1929.0,21.0,33.0,123.0,Federal,"(42.27687306500047, -72.08268985899963)"
3,"[Tennessee, (35.680943063000484, -85.774486421...",101.0,3.8,30.0,65100.0,3.5,727.0,45.0,30.0,82.0,State,"(35.680943063000484, -85.77448642199965)"
4,"[Oklahoma, (35.472034350000456, -97.5210684549...",97.0,6.1,42.0,39000.0,3.6,1872.0,24.0,19.0,131.0,Federal,"(35.472034350000456, -97.52106845499969)"

## 3. Statistics Summary (a) (10 Points)
Write a Python function named statistics_summary() that summarizes the "State	Number of Fatalities, 2012" distribution. The function include: mean, standard deviation, median,maximum number of fatalities, the index of the maximum number of fatalities, the state name of the maximum number of fatalities, and the histogram plot.

## 4. Statistics Summary (b) (10 Points)

By using for loop, show the statistics summary of "Number of Injuries/Illnesses 2012", "Penalties FY 2013", "Inspectors", and "Years to Inspect Each Workplace"

## 5. Show the Pair Plot  (30 Points)

Divide the data into two populations based on the "state number of Fatalities, 2012":

one group with Fatalities >= 100, and

the other with Fatalities < 100.

Create the pair plots among all variables, and replace the diagonal plots with 1D histograms.